# Generated by Django 4.2.4 on 2023-09-05 02:36

import core.fields.encrypted_char_field
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('password', core.fields.encrypted_char_field.Sha256EncryptedCharField(help_text='비밀번호', max_length=300, null=True)),
                ('username', models.CharField(help_text='이름', max_length=50, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('email', models.EmailField(help_text='이메일 주소', max_length=254, unique=True)),
                ('gender', models.CharField(help_text='성별(M:남, F:여, N:미설정)', max_length=1, null=True)),
                ('birthday', models.CharField(help_text='생년월일', max_length=8, null=True)),
                ('status', models.CharField(choices=[('join', '가입'), ('leave', '탈퇴')], help_text='상태', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='최종 로그인 일시', null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('leave_at', models.DateTimeField(help_text='탈퇴일', null=True)),
            ],
            options={
                'db_table': 't_mb_member',
                'ordering': ['-seq'],
                'unique_together': {('username', 'email')},
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('paid_at', models.DateTimeField(help_text='구매 일시', null=True)),
                ('status', models.CharField(choices=[('paid', '구매 완료'), ('some_refund', '일부 환불'), ('refund', '전체 환불')], help_text='상태', max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('member_seq', models.ForeignKey(db_column='member_seq', db_constraint=False, help_text='회원 일련번호', on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 't_usr_order',
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('paid', '구매 완료'), ('refund', '환불')], help_text='상태', max_length=30)),
                ('price', models.IntegerField(default=0, help_text='판매가')),
                ('paid_at', models.DateTimeField(help_text='구매 일시', null=True)),
                ('refund_at', models.DateTimeField(help_text='환불 일시', null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('music_seq', models.ForeignKey(db_column='music_seq', db_constraint=False, help_text='곡 일련번호', on_delete=django.db.models.deletion.CASCADE, to='content.music')),
                ('order_seq', models.ForeignKey(db_column='order_seq', db_constraint=False, help_text='주문 일련번호', on_delete=django.db.models.deletion.CASCADE, to='member.order')),
            ],
            options={
                'db_table': 't_usr_order_product',
                'ordering': ['-seq'],
            },
        ),
    ]
