# Generated by Django 4.2.4 on 2023-09-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_groups_member_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='leave_at',
            field=models.DateTimeField(blank=True, help_text='탈퇴일', null=True),
        ),
    ]
