# Generated by Django 4.2.4 on 2023-11-27 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_simplicity_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('email', 'tag')},
        ),
    ]
