# Generated by Django 4.2.4 on 2023-09-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_order_member_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='music_seq',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_seq',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
