# Generated by Django 4.2.4 on 2023-11-30 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='이름', max_length=120)),
                ('representation_image', models.CharField(help_text='대표이미지', max_length=512, null=True)),
                ('org_price', models.IntegerField(help_text='소비자가')),
                ('sale_price', models.IntegerField(help_text='판매가')),
                ('discount_rate', models.SmallIntegerField(help_text='할인율')),
                ('tax_flag', models.SmallIntegerField(default=1, help_text='과세여부')),
                ('counsel_telephone', models.CharField(help_text='소비자상담번호', max_length=64, null=True)),
                ('status', models.CharField(choices=[('enable', '판매중'), ('disable', '판매 중지'), ('sanctions', '제재')], default='disable', help_text='상태', max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('create_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, help_text='생성자', max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller_seq', models.ForeignKey(db_column='seller_seq', help_text='판매자 일련번호(FK)', on_delete=django.db.models.deletion.PROTECT, to='seller.seller')),
                ('update_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, help_text='수정자', max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_pd_product',
                'ordering': ['-seq'],
            },
        ),
    ]
