# Generated by Django 4.2.4 on 2023-09-13 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0007_remove_orderproduct_music_seq_and_more'),
        ('content', '0005_remove_albumadditionalinfo_album_seq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('paid_at', models.DateTimeField(help_text='구매 일시', null=True)),
                ('status', models.CharField(choices=[('paid', '구매 완료'), ('some_refund', '일부 환불'), ('refund', '전체 환불')], help_text='상태', max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('member_seq', models.OneToOneField(db_column='member_seq', db_constraint=False, help_text='회원 일련번호', on_delete=django.db.models.deletion.CASCADE, related_name='member', to='member.member')),
            ],
            options={
                'db_table': 't_usr_order',
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('paid', '구매 완료'), ('refund', '환불')], help_text='상태', max_length=30)),
                ('price', models.IntegerField(default=0, help_text='판매가')),
                ('paid_at', models.DateTimeField(help_text='구매 일시', null=True)),
                ('refund_at', models.DateTimeField(help_text='환불 일시', null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('music_seq', models.ForeignKey(db_column='music_seq', db_constraint=False, help_text='곡 일련번호', on_delete=django.db.models.deletion.CASCADE, to='content.music')),
                ('order_seq', models.ForeignKey(db_column='order_seq', db_constraint=False, help_text='주문 일련번호', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 't_usr_order_product',
                'ordering': ['-seq'],
            },
        ),
    ]
