### 로그인
POST http://{{BASE_URL}}:{{PORT}}/auth/login
Content-Type: application/json

{
  "username": "test1",
  "password": "1234"
}

> {%
client.test("응답이 정상적으로 왔는지 확인한다", function() {
    client.log("응답코드= "+response.status);
    client.assert(response.status === 200 || response.status === 302,"응답 실패");

    client.global.set("access_token", response.body.data.auth.access_token);
    client.global.set("refresh_token", response.body.data.auth.refresh_token);
    client.log('Bearer ' + client.global.get("access_token"))
});
%}

### 관리자 로그아웃
POST http://{{BASE_URL}}:{{PORT}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{access_token}}

### verify token
POST http://{{BASE_URL}}:{{PORT}}/auth/token/verify
Content-Type: application/json

{
  "access_token": "{{access_token}}"
}

### refresh token
POST http://{{BASE_URL}}:{{PORT}}/auth/token/refresh
Content-Type: application/json

{
  "refresh_token": "{{refresh_token}}"
}

> {%
client.test("응답이 정상적으로 왔는지 확인한다", function() {
    client.log("응답코드= "+response.status);
    client.assert(response.status === 200 || response.status === 302,"응답 실패");
    client.log(response.headers.valuesOf("Set-Cookie")[0])
    client.log(response.headers.valuesOf("Set-Cookie")[1])
    client.log(response.headers.valuesOf("Set-Cookie")[2])

    client.global.set("access_token", response.body.data.auth.access_token);
    client.global.set("refresh_token", response.body.data.auth.refresh_token);
    client.log('Bearer ' + client.global.get("access_token"))
});
%}

### API 권한 Test
GET http://{{BASE_URL}}:{{PORT}}/auth/permission_test?page=1&page_size=100&ordering=-seq
Content-Type: application/json
Authorization: Bearer {{access_token}}

### API 권한 Test
GET http://{{BASE_URL}}:{{PORT}}/auth/permission_test/62
Content-Type: application/json
Authorization: Bearer {{access_token}}

### API 권한 Pass Test
GET http://{{BASE_URL}}:{{PORT}}/auth/permission_any_test?page=1&page_size=100&ordering=-seq
Content-Type: application/json
#Authorization: Bearer {{access_token}}
