### 회원 조회
GET http://{{BASE_URL}}:{{PORT}}/member
Authorization: Bearer {{ACCESS_TOKEN}}

### 회원 상세 조회
GET http://{{BASE_URL}}:{{PORT}}/member/1
Authorization: Bearer {{ACCESS_TOKEN}}

### 회원 가입
POST http://{{BASE_URL}}:{{PORT}}/member/register
Content-Type: application/json

{
  "username": "bomig88",
  "password": "test1234",
  "birthday": "19880825",
  "gender": "F",
  "email": "bomig88@gmail.com",
  "tag": "super_manager"
}

### 회원 탈퇴
POST http://{{BASE_URL}}:{{PORT}}/member/1/leave
Content-Type: application/json
Authorization: Bearer {{ACCESS_TOKEN}}

{

}