# Generated by Django 4.2.4 on 2023-11-30 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seq', models.BigAutoField(help_text='일련번호(PK)', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='이름', max_length=50)),
                ('representative', models.CharField(help_text='대표자명', max_length=50)),
                ('corporate_registration_number', models.CharField(help_text='법인등록번호', max_length=50, null=True, unique=True)),
                ('business_registration_number', models.CharField(help_text='사업자등록번호', max_length=50, unique=True)),
                ('communication_seller_number', models.CharField(help_text='통신판매업신고번호', max_length=50, unique=True)),
                ('customer_center', models.CharField(help_text='고객센터 연락처', max_length=50)),
                ('sanction_cnt', models.IntegerField(default=0, help_text='재제횟수')),
                ('status', models.CharField(choices=[('join', '가입'), ('sanctions', '제재'), ('leave', '탈퇴')], default='join', help_text='상태', max_length=30)),
                ('tag', models.CharField(choices=[('individual', '개인 사업체'), ('incorporated', '법인 사업체'), ('tax_player', '간이 과세자')], default='individual', help_text='분류', max_length=30)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='생성일시')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='수정일시')),
                ('create_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, help_text='생성자', max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('update_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, help_text='수정자', max_length=64, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_mb_seller',
                'ordering': ['-seq'],
            },
        ),
    ]
