# Generated by Django 4.2.4 on 2023-09-05 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_code',
        ),
        migrations.RemoveField(
            model_name='albumdetail',
            name='album_code',
        ),
        migrations.RemoveField(
            model_name='artistdetail',
            name='artist_code',
        ),
        migrations.RemoveField(
            model_name='music',
            name='album_code',
        ),
        migrations.AddField(
            model_name='album',
            name='artist_seq',
            field=models.OneToOneField(db_column='artist_seq', db_constraint=False, default=0, help_text='아티스트 일련번호', on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='content.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumdetail',
            name='album_seq',
            field=models.OneToOneField(db_column='album_seq', db_constraint=False, default=0, help_text='앨범 일련번호', on_delete=django.db.models.deletion.CASCADE, related_name='album_detail', to='content.album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistdetail',
            name='artist_seq',
            field=models.OneToOneField(db_column='artist_seq', db_constraint=False, default=0, help_text='아티스트 일련번호', on_delete=django.db.models.deletion.CASCADE, related_name='artist_detail', to='content.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='music',
            name='album_seq',
            field=models.ForeignKey(db_column='album_seq', db_constraint=False, default=0, help_text='앨범 코드', on_delete=django.db.models.deletion.CASCADE, to='content.album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicdetail',
            name='music_seq',
            field=models.OneToOneField(db_column='music_seq', db_constraint=False, help_text='곡 일련번호', on_delete=django.db.models.deletion.CASCADE, related_name='music_detail', to='content.music'),
        ),
    ]
