# Generated by Django 4.2.4 on 2023-09-13 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_albumdetail_albumadditionalinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumadditionalinfo',
            name='album_seq',
        ),
        migrations.RemoveField(
            model_name='artistadditionalinfo',
            name='artist_seq',
        ),
        migrations.RemoveField(
            model_name='musicadditionalinfo',
            name='music_seq',
        ),
        migrations.AddField(
            model_name='album',
            name='album_additional_info_seq',
            field=models.OneToOneField(db_column='album_additional_info_seq', db_constraint=False, help_text='앨범 추가 정보 일련번호', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.albumadditionalinfo'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_additional_info_seq',
            field=models.OneToOneField(db_column='artist_additional_info_seq', db_constraint=False, help_text='아티스트 추가 정보 일련번호', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.artistadditionalinfo'),
        ),
        migrations.AddField(
            model_name='music',
            name='music_additional_info_seq',
            field=models.OneToOneField(db_column='music_additional_info_seq', db_constraint=False, help_text='곡 추가 정보 일련번호', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.musicadditionalinfo'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist_seq',
            field=models.OneToOneField(db_column='artist_seq', db_constraint=False, help_text='아티스트 일련번호', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(help_text='아티스트 명', max_length=80),
        ),
        migrations.AlterField(
            model_name='music',
            name='album_seq',
            field=models.ForeignKey(db_column='album_seq', db_constraint=False, help_text='앨범 코드', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(help_text='곡 명', max_length=80),
        ),
    ]
