# Generated by Django 4.2.4 on 2023-12-01 09:34

import core.fields.current_user_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_by',
            field=core.fields.current_user_field.CurrentUserField(default='admin', help_text='생성자', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_by',
            field=core.fields.current_user_field.CurrentUserField(default='admin', help_text='수정자', max_length=64),
        ),
    ]
