# Generated by Django 4.2.4 on 2023-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_unique_together_member_simplicity_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='simplicity_key',
            field=models.CharField(help_text='간편 인증 값', max_length=320, null=True),
        ),
    ]
