# Generated by Django 4.2.4 on 2023-11-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_member_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='simplicity_key',
        ),
        migrations.AlterField(
            model_name='member',
            name='tag',
            field=models.CharField(choices=[('basic_user', '일반 사용자'), ('manager', '관리자'), ('super_manager', '상위 관리자')], default='basic_user', help_text='분류', max_length=30),
        ),
    ]
